services:
  rodel-pos:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${APP_PORT}:8000"

    networks:
      rodel_pos_net:
        ipv4_address: ${APP_IP}
      rodelsoft_net: {}

networks:
  rodel_pos_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}

  rodelsoft_net:
    external: true
    name: ${DOCKER_EXTERNAL_NETWORK}